"""Minted platform adapter — auto-generated by copy_runtime_modules.

Platform is baked at mint time.  No harness.* imports.
"""

from runtime_adapter import get_adapter as _get_adapter


def get_adapter():
    """No-arg shim — delegates to runtime_adapter with platform baked in."""
    return _get_adapter("claude")
