"""runtime_slice — single source of truth for the harness runtime artifact.

This module owns:

    RUNTIME_FILE_MAP  — one mapping from deployed ``src/<name>`` to package-
                        relative source path (under ``src/harness/``), or None
                        for files that are *emitted* at mint time rather than
                        copied from a source file.

    rewrite_imports   — shared import-rewrite function used by both
                        ``copy_runtime_modules`` (mint path) and
                        ``reproduce_runtime_file`` (update path).

    emit_platform_adapter — shared emitter for the ``platform_adapter.py``
                            shim; used by both mint and reproduce so the
                            template text lives in exactly one place (D4).

    reproduce_runtime_file — returns the exact bytes/text that would be
                             deployed for ``src/<name>`` without touching disk.
                             Used by the update machinery to compare "theirs".

Failure modes:
  - ``reproduce_runtime_file`` raises ``KeyError`` for an unknown ``name``.
  - Missing source files raise ``FileNotFoundError`` (propagated from
    ``Path.read_text``).
  - ``platform_profiles.json`` is reproduced verbatim (no rewrite).
  - ``__init__.py`` is always the empty string.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# D5 — One runtime file map
# ---------------------------------------------------------------------------
# Keys: deployed name relative to src/ (no leading "src/").
# Values: package-relative path under src/harness/ — or None for emitted files.

#: Deployed ``src/<name>`` → package-relative source under ``src/harness/``,
#: or ``None`` if the file is emitted (generated, not copied).
RUNTIME_FILE_MAP: dict[str, Optional[str]] = {
    "dispatcher.py":             "runtime/dispatcher.py",
    "llm_client.py":             "runtime/llm_client.py",
    "context_builder.py":        "runtime/context_builder.py",
    "langfuse_compat.py":        "runtime/langfuse_compat.py",
    "langfuse_instrumentation.py": "runtime/langfuse_instrumentation.py",
    "discovery_engine.py":       "init/discovery_engine.py",
    "runtime_adapter.py":        "adapters/runtime_adapter.py",
    "profile.py":                "adapters/profile.py",
    "platform_profiles.json":    "adapters/platform_profiles.json",
    "platform_adapter.py":       None,   # emitted — platform baked in at mint
    "__init__.py":               None,   # emitted — always empty
}

# ---------------------------------------------------------------------------
# D4 — Shared import-rewrite function
# ---------------------------------------------------------------------------

# Regex covers harness.runtime.*, harness.init.*, harness.adapters.*
_HARNESS_FROM_RE = re.compile(r"from harness\.(?:runtime|init|adapters)\.")
_HARNESS_IMPORT_RE = re.compile(r"import harness\.(?:runtime|init|adapters)\.")


def rewrite_imports(text: str) -> str:
    """Strip harness sub-package prefixes so deployed modules use flat imports.

    Transforms:
        ``from harness.runtime.X import Y``  →  ``from X import Y``
        ``from harness.init.X import Y``     →  ``from X import Y``
        ``from harness.adapters.X import Y`` →  ``from X import Y``
        ``import harness.runtime.X as Y``    →  ``import X as Y``
        (same for init / adapters)
    """
    patched = _HARNESS_FROM_RE.sub("from ", text)
    patched = _HARNESS_IMPORT_RE.sub("import ", patched)
    return patched


# ---------------------------------------------------------------------------
# D4 — Shared platform_adapter emitter
# ---------------------------------------------------------------------------

_KNOWN_PLATFORMS: frozenset[str] = frozenset(
    {"claude", "gemini", "codex", "cursor", "generic"}
)


def emit_platform_adapter(platform_id: str) -> str:
    """Return the content of ``platform_adapter.py`` for the given platform.

    Resolves unknown platform IDs to ``"generic"`` (same fallback as
    ``copy_runtime_modules``).  The emitted shim has zero ``harness.*`` imports;
    it relies on ``runtime_adapter`` being deployed alongside it.

    Args:
        platform_id: The target platform (e.g. ``"claude"``).

    Returns:
        The full text of the emitted ``platform_adapter.py``.
    """
    resolved = platform_id if platform_id in _KNOWN_PLATFORMS else "generic"
    return (
        '"""Minted platform adapter — auto-generated by copy_runtime_modules.\n\n'
        "Platform is baked at mint time.  No harness.* imports.\n"
        '"""\n\n'
        "from runtime_adapter import get_adapter as _get_adapter\n\n\n"
        "def get_adapter():\n"
        f'    """No-arg shim — delegates to runtime_adapter with platform baked in."""\n'
        f'    return _get_adapter("{resolved}")\n'
    )


# ---------------------------------------------------------------------------
# reproduce_runtime_file — on-demand artifact reproduction
# ---------------------------------------------------------------------------

def reproduce_runtime_file(
    name: str,
    *,
    platform: str,
    package_root: Path,
) -> str:
    """Return the text that would be deployed as ``src/<name>``.

    This is the read-only, no-side-effect counterpart of the write path in
    ``copy_runtime_modules``.  It is used by the update machinery to build the
    "theirs" side of a three-way merge without writing to disk.

    Args:
        name:         Deployed filename within ``src/``, e.g. ``"dispatcher.py"``.
        platform:     Platform ID forwarded to ``emit_platform_adapter``.
        package_root: Absolute path to the harness package root
                      (the directory containing ``runtime/``, ``adapters/``,
                      ``init/`` — i.e. ``src/harness/``).

    Returns:
        The full text content that ``copy_runtime_modules`` would write.

    Raises:
        KeyError: ``name`` is not in ``RUNTIME_FILE_MAP``.
        FileNotFoundError: The source file referenced by the map does not exist.
    """
    if name not in RUNTIME_FILE_MAP:
        raise KeyError(f"Unknown runtime file: {name!r}")

    source_rel = RUNTIME_FILE_MAP[name]

    # --- Emitted files -------------------------------------------------------
    if source_rel is None:
        if name == "platform_adapter.py":
            return emit_platform_adapter(platform)
        if name == "__init__.py":
            return ""
        # Future sentinel: emitted files with no dedicated emitter.
        return ""  # pragma: no cover

    # --- Verbatim copy (non-Python) ------------------------------------------
    if not name.endswith(".py"):
        src_path = package_root / source_rel
        return src_path.read_text(encoding="utf-8")

    # --- Python source with import rewrite -----------------------------------
    src_path = package_root / source_rel
    text = src_path.read_text(encoding="utf-8")
    return rewrite_imports(text)
